### ISSUE TITLE
Alfred sets `ACCESS_TOKEN` env var as empty string

### ISSUE THREAD

**Issue by pgilad** [jovobe/alfred-confluence-workflow#2]
I find Alfred sets the `ACCESS_TOKEN` env var as empty string (I use username/password) and the code doesn't check if the variable is empty, and thus uses `bearer_auth` authentication method which fails.

The check for using access_token should also verify if the string is empty and if so - use username/password

**Comment by jovobe** [comment]
This should be fixed in a14b33d5d678d1836ec6d6c294b95c4a4ba9552e. Please comment to this issue if the bug still exists.
