### ISSUE TITLE
Code 101: thread 'main' panicked at 'Request failed with status code "401 Unauthorized". Check your BASE_URL and auth credentials!'

### ISSUE THREAD

**Issue by xerosanyam** [jovobe/alfred-confluence-workflow#5]
Tried all combinations, can't get it to run 
<img width="843" alt="image" src="https://user-images.githubusercontent.com/3167278/168462651-35929526-8197-405f-a1e5-a132ec0d4ac8.png">

**Comment by Canis1Majoris** [comment]
Same. 
Tried token / token + username / token + username + token in password field

**Comment by xerosanyam** [comment]
yes, nothing worked.

**Comment by mpavlikWandera** [comment]
same here

**Comment by CodenixLR** [comment]
Same issue for me too.

**Comment by jovobe** [comment]
Thank you guys for reporting this and confirming the issue exists! To fix it, I need some more information. Could you please provide some information about your environment? The following would help me to try to reproduce the error:
1. Which Version of macOS are you on, and are you on Intel or Apple Silicon?
2. What is the exact URL you entered into the `BASE_URL` parameter? If this information is sensitive, could you tell me if your confluence is hosted on premise, or you are using the cloud version?
3. Are you using some kind of VPN or Firewall?

**Comment by sank8dalvi** [comment]
I am a confluence cloud user and this issue was resolved for me by obtaining token from [here](https://id.atlassian.com/manage/api-tokens), setting BASE_URL without trailing slashes, ACCESS_TOKEN should be empty, USERNAME as my confluence email id and PASSWORD as the generated api token.

**Comment by learn2reid** [comment]
Same for me, it used to work then I changed my password & it no longer works. I know I'm using the right password. Using username, password, & base url fields.

**Comment by jovobe** [comment]
Thanks for your feedback! I'm glad everything is working now as expected. I'm going to close the ticket then.
