### ISSUE TITLE
acw-x86 cannot be opened because the developer cannot be verified

### ISSUE THREAD

**Issue by basvdijk** [jovobe/alfred-confluence-workflow#6]
Unfortunately I get this error when running the workflow on MacOS 12.4

![image](https://user-images.githubusercontent.com/644550/180056732-a5a0bbc1-4f3d-4a14-afb4-3b6cd5700247.png)

**Comment by skyzyx** [comment]
Yeah, it needs to be notarized by Apple. I started working on a rewrite of the old Python2 extension in Go a few days before I saw this, but I drew the same conclusion — the workflow will need to be notarized.

Not sure what @jovobe’s plans are for this. As an alternative, you can compile it yourself to avoid the notarization requirement.

**Comment by basvdijk** [comment]
Thanks for your reply! Since I am a NodeJS developer I decided to make my own workflow based on NodeJS https://github.com/basvdijk/alfred-confluence-search

**Comment by yi-mei-wang** [comment]
> As an alternative, you can compile it yourself to avoid the notarization requirement.

@skyzyx Do you mind teaching me how to go about doing that?

**Comment by jovobe** [comment]
@skyzyx my plan is to provide a notarized release right here. Unfortunately, I just did not have the time to get it done.

**Comment by jovobe** [comment]
@yi-mei-wang absolutely! You need to go through the following steps:
1. Install the Rust toolchain. [Here](https://www.rust-lang.org/learn/get-started) is the best resource to start.
2. As described [here](https://github.com/jovobe/alfred-confluence-workflow#development), you need to install an additional build target depending on which platform you are on.
3. Clone [this repository](https://github.com/jovobe/alfred-confluence-workflow) to your machine.
4. Enter the repository and just run `make`. The workflow should then open up, and you are ready to go.

**Comment by skyzyx** [comment]
> > As an alternative, you can compile it yourself to avoid the notarization requirement.
> 
> @skyzyx Do you mind teaching me how to go about doing that?

I'm a little late, but @jovobe already answered the question. It's documented under the [**Development**](https://github.com/jovobe/alfred-confluence-workflow#development) header in the README.

**Comment by yi-mei-wang** [comment]
Awesome, thanks guys! @jovobe @skyzyx. Works perfectly now!

**Comment by jovobe** [comment]
@basvdijk there is a brand-new release, which should resolve this issue. Could anyone please confirm that it is working? You can get the latest release right here: https://github.com/jovobe/alfred-confluence-workflow/releases
